package dev.sepler.vaultbox.dao.model;

import lombok.Builder;
import lombok.Getter;
import lombok.Value;
import lombok.With;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbIgnore;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.Instant;

@Value
@With
@Builder
@DynamoDbImmutable(builder = VaultItem.VaultItemBuilder.class)
public class VaultItem {

    @With(onMethod = @__({@DynamoDbIgnore}))
    @Getter(onMethod = @__({@DynamoDbPartitionKey}))
    String id;

    @With(onMethod = @__({@DynamoDbIgnore}))
    String name;

    @With(onMethod = @__({@DynamoDbIgnore}))
    VaultItemStatus status;

    @With(onMethod = @__({@DynamoDbIgnore}))
    String statusReason;

    @With(onMethod = @__({@DynamoDbIgnore}))
    long sizeInBytes;

    @With(onMethod = @__({@DynamoDbIgnore}))
    @Getter(onMethod = @__({@DynamoDbAutoGeneratedTimestampAttribute}))
    Instant lastUpdated;

}
